"""DCC-neutral rig description and validation."""

from .fit_container import (
    LOCKED_FIT_CHANNELS,
    FitContainerDisplayStyle,
    FitContainerIssue,
    FitContainerShape,
    FitContainerSpec,
    FitContainerState,
    FitUpAxis,
    audit_fit_container,
)
from .fit_hierarchy import (
    TRANSLATION_AXES,
    FitHierarchyIssue,
    FitHierarchyNode,
    FitHierarchyPolicy,
    FitHierarchySnapshot,
    FitHierarchyValidationError,
    audit_fit_hierarchy,
)
from .fit_metadata import (
    FitJointIssue,
    FitJointField,
    FitJointFieldEdit,
    FitJointMetadata,
    FitJointPatch,
    FitJointValidationError,
    audit_fit_joint,
    fit_joint_value,
    predict_fit_joint_metadata,
)
from .fit_settings import (
    FIT_GEOMETRY_TYPES,
    FitSkeletonField,
    FitSkeletonIssue,
    FitSkeletonSetting,
    FitSkeletonSettings,
    FitSkeletonValidationError,
    FitSkeletonValue,
    audit_fit_skeleton_settings,
    default_fit_skeleton_settings,
)
from .fit_position import (
    FitJointPositionChange,
    FitJointPositionEdit,
    FitJointPositionPatch,
    FitPositionValidationError,
    plan_fit_joint_position_changes,
)
from .fit_template import (
    FitJointSpec,
    FitTemplateIssue,
    FitTemplateSpec,
    audit_fit_template_snapshot,
    minimal_body_fit_template,
    ordered_fit_joints,
    validate_fit_template,
)
from .joint_labels import JointLabel, JointLabelValidationError
from .model import ConstraintSpec, LimbSpec, NodeSpec, RigPlan
from .matrix import (
    IDENTITY_MATRIX,
    Matrix44,
    almost_equal,
    frame_from_y,
    matrix44,
    multiply,
    rotation_y_matrix,
    rotation_z_matrix,
    rows,
    translation_matrix,
    transpose_flat,
    with_translation,
)
from .validation import PlanValidationError, validate_plan

__all__ = [
    "ConstraintSpec",
    "FitContainerDisplayStyle",
    "FitContainerIssue",
    "FitContainerShape",
    "FitContainerSpec",
    "FitContainerState",
    "FitHierarchyIssue",
    "FitHierarchyNode",
    "FitHierarchyPolicy",
    "FitHierarchySnapshot",
    "FitHierarchyValidationError",
    "FitJointIssue",
    "FitJointField",
    "FitJointFieldEdit",
    "FitJointMetadata",
    "FitJointPatch",
    "FitJointPositionChange",
    "FitJointPositionEdit",
    "FitJointPositionPatch",
    "FitJointSpec",
    "FitJointValidationError",
    "FitUpAxis",
    "FIT_GEOMETRY_TYPES",
    "FitSkeletonField",
    "FitSkeletonIssue",
    "FitSkeletonSetting",
    "FitSkeletonSettings",
    "FitSkeletonValidationError",
    "FitSkeletonValue",
    "FitPositionValidationError",
    "FitTemplateIssue",
    "FitTemplateSpec",
    "IDENTITY_MATRIX",
    "JointLabel",
    "JointLabelValidationError",
    "LOCKED_FIT_CHANNELS",
    "LimbSpec",
    "Matrix44",
    "NodeSpec",
    "PlanValidationError",
    "RigPlan",
    "TRANSLATION_AXES",
    "almost_equal",
    "audit_fit_hierarchy",
    "audit_fit_container",
    "audit_fit_joint",
    "audit_fit_skeleton_settings",
    "audit_fit_template_snapshot",
    "default_fit_skeleton_settings",
    "frame_from_y",
    "fit_joint_value",
    "matrix44",
    "minimal_body_fit_template",
    "multiply",
    "plan_fit_joint_position_changes",
    "ordered_fit_joints",
    "predict_fit_joint_metadata",
    "rotation_y_matrix",
    "rotation_z_matrix",
    "rows",
    "translation_matrix",
    "transpose_flat",
    "validate_plan",
    "validate_fit_template",
    "with_translation",
]
